FROM ruby:2.4.1-alpine
RUN apk upgrade --no-cache && apk add --no-cache bash
SHELL [ "/bin/bash" , "-c" ]

RUN mkdir -p /fakes3_root/data
WORKDIR /fakes3_root

# install fake-s3
RUN gem install fakes3

ENV PORT 4567

# run fake-s3
ENTRYPOINT [ "fakes3" ]
CMD [ "-r",  "/fakes3_root", "-p",  "4567", "--license", "$FAKE_S3_LICENSE" ]
