FROM debian:stretch-slim
MAINTAINER Larry Howard <larry.howard@vanderbilt.edu>

SHELL [ "/bin/bash" , "-c" ]
ENV DEBIAN_FRONTEND noninteractive

# install Ruby
RUN apt-get update && apt-get install -yqq ruby rubygems-integration --no-install-recommends

# install fake-s3
RUN gem install fakes3

# run fake-s3
RUN mkdir -p /fakes3_root
ENTRYPOINT [ "/usr/local/bin/fakes3" ]
CMD [ "-r",  "/fakes3_root", "-p",  "4569", "--license", "${FAKE_S3_LICENSE}" ]
